package io.joshatron.budgetlibrary.exception;

public enum ErrorCode {
    INVALID_TRANSACTION,
    INVALID_VENDOR,
    INVALID_TYPE,
    INVALID_ACCOUNT,
    TRANSACTION_EXISTS,
    VENDOR_EXISTS,
    INVALID_VENDOR_MAPPING,
    VENDOR_HAS_DEPENDANT_TRANSACTIONS,
    DATABASE_ERROR
}
