package io.joshatron.budgetlibrary.exception;

public enum ErrorCode {
    INVALID_TRANSACTION,
    INVALID_VENDOR,
    INVALID_TYPE,
    INVALID_ACCOUNT,
    INVALID_STRING,
    INVALID_TIMESTAMP,
    INVALID_MONEY,
    INVALID_SESSION,
    INVALID_INITIALIZATION,
    NO_RESULT_FOUND,
    TOO_MANY_RESULTS_FOUND,
    STRING_NOT_IN_LIST,
    STRING_ALREADY_IN_LIST,
    IO_ERROR
}
